### PR TITLE
Data preparation and PyTorch dataset implementation

### PR DESCRIPTION
**Pull request by matzewolf**
Covers approx. the files with S0 and S1 in the reference, including an implementation of a PyTorch dataset. Model not included yet.

### CODE REVIEW

**Comment by AhmedAbdel-Aal** [comment]
I went through the code. I recommend 1- docstring description for each function, 2- comments for each code section/line

**Comment by AhmedAbdel-Aal** [comment]
since data combindation and preparation are 2 different tasks, I would recommend splitting the tasks on 2 different files

**Comment by AhmedAbdel-Aal** [comment]
We don't need to rotate train-set point clouds?

**Comment by matzewolf** [comment]
> I went through the code. I recommend 1- docstring description for each function, 2- comments for each code section/line

Yeah, makes sense. Some section are more or less copied from the original repo, so I have to figure out what exactly is happening there.

**Comment by matzewolf** [comment]
> since data combindation and preparation are 2 different tasks, I would recommend splitting the tasks on 2 different files

I like it more in one file tbh. Reason is we can attach a script to it in the main function that does everything at once, just like I implemented it. The separation feels at bit artificial and makes more effort to document (i.e. what step comes first etc. instead of "just call the preparation script")

**Comment by matzewolf** [comment]
> We don't need to rotate train-set point clouds?

The reference code doesn't do this, so it's not high prio. We can add this later however and see what changes.

**Review by AhmedAbdel-Aal — APPROVED** [review]

**Pull request merged**
